"""add_deleted_at_soft_delete_columns

Revision ID: f514fcb81c72
Revises: 976b9b9c96d4
Create Date: 2026-05-03 23:49:42.688425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f514fcb81c72'
down_revision: Union[str, None] = '976b9b9c96d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference_period', sa.String(), nullable=False),
    sa.Column('employment_status', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('isco_code', sa.String(), nullable=True),
    sa.Column('isic_code', sa.String(), nullable=True),
    sa.Column('isced_level', sa.Integer(), nullable=True),
    sa.Column('hours_per_week', sa.Float(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_register_id'), 'person_register', ['id'], unique=False)
    op.create_index(op.f('ix_person_register_user_id'), 'person_register', ['user_id'], unique=False)
    op.add_column('survey_responses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_survey_responses_deleted_at'), 'survey_responses', ['deleted_at'], unique=False)
    op.add_column('survey_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_survey_sessions_deleted_at'), 'survey_sessions', ['deleted_at'], unique=False)
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_index(op.f('ix_survey_sessions_deleted_at'), table_name='survey_sessions')
    op.drop_column('survey_sessions', 'deleted_at')
    op.drop_index(op.f('ix_survey_responses_deleted_at'), table_name='survey_responses')
    op.drop_column('survey_responses', 'deleted_at')
    op.drop_index(op.f('ix_person_register_user_id'), table_name='person_register')
    op.drop_index(op.f('ix_person_register_id'), table_name='person_register')
    op.drop_table('person_register')
    # ### end Alembic commands ###
