"""Exact display-label aliases for conditional questionnaire answers.

Keep these aligned with frontend/components/survey-options.js. Canonical
button values are server-validated; these aliases also support typed labels
and older clients that send only the displayed answer.
"""

OPTION_VALUE_ALIASES = {'employment_status': {'employed': 'employed',
                       'unemployed': 'unemployed',
                       'not_in_labour_force': 'not_in_labour_force',
                       'not in the labour force': 'not_in_labour_force',
                       'موظف': 'employed',
                       'عاطل عن العمل': 'unemployed',
                       'خارج سوق العمل': 'not_in_labour_force',
                       'ملازم': 'employed',
                       'بے روزگار': 'unemployed',
                       'افرادی قوت سے باہر': 'not_in_labour_force',
                       'नियोजित': 'employed',
                       'बेरोजगार': 'unemployed',
                       'श्रम बल से बाहर': 'not_in_labour_force'},
 'education_level': {'no_formal': 'no_formal',
                     'primary': 'primary',
                     'secondary': 'secondary',
                     'diploma': 'diploma',
                     'bachelor': 'bachelor',
                     'master': 'master',
                     'phd': 'phd',
                     'no formal education': 'no_formal',
                     "bachelor's degree": 'bachelor',
                     "master's degree": 'master',
                     'phd or higher': 'phd',
                     'بدون تعليم رسمي': 'no_formal',
                     'ابتدائي': 'primary',
                     'ثانوي': 'secondary',
                     'دبلوم': 'diploma',
                     'بكالوريوس': 'bachelor',
                     'ماجستير': 'master',
                     'دكتوراه': 'phd',
                     'کوئی رسمی تعلیم نہیں': 'no_formal',
                     'ابتدائی': 'primary',
                     'ثانوی': 'secondary',
                     'ڈپلومہ': 'diploma',
                     'بیچلر ڈگری': 'bachelor',
                     'ماسٹر ڈگری': 'master',
                     'پی ایچ ڈی یا اس سے زیادہ': 'phd',
                     'कोई औपचारिक शिक्षा नहीं': 'no_formal',
                     'प्राथमिक': 'primary',
                     'माध्यमिक': 'secondary',
                     'डिप्लोमा': 'diploma',
                     'स्नातक': 'bachelor',
                     'स्नातकोत्तर': 'master',
                     'पीएचडी या उच्चतर': 'phd',
                     'walang pormal na edukasyon': 'no_formal',
                     'primarya': 'primary',
                     'sekundarya': 'secondary',
                     'batsilyer': 'bachelor',
                     'doktorado o mas mataas': 'phd'},
 'employment_nature': {'paid_employee': 'paid_employee',
                       'employer': 'employer',
                       'self_employed': 'self_employed',
                       'contributing_family_member': 'contributing_family_member',
                       'paid employee': 'paid_employee',
                       'self-employed': 'self_employed',
                       'contributing family worker': 'contributing_family_member',
                       'موظف براتب': 'paid_employee',
                       'صاحب عمل': 'employer',
                       'عمل حر': 'self_employed',
                       'عامل عائلي مساهم': 'contributing_family_member',
                       'تنخواہ دار ملازم': 'paid_employee',
                       'آجر': 'employer',
                       'خود ملازم': 'self_employed',
                       'خاندانی کارکن': 'contributing_family_member',
                       'वेतनभोगी कर्मचारी': 'paid_employee',
                       'नियोक्ता': 'employer',
                       'स्व-रोज़गार': 'self_employed',
                       'परिवार का सहायक कार्यकर्ता': 'contributing_family_member',
                       'bayad na empleyado': 'paid_employee'},
 'nationality': {'uae_national': 'uae_national',
                 'indian': 'indian',
                 'pakistani': 'pakistani',
                 'filipino': 'filipino',
                 'bangladeshi': 'bangladeshi',
                 'egyptian': 'egyptian',
                 'british': 'british',
                 'other': 'other',
                 'emirati': 'uae_national',
                 'إماراتي': 'uae_national',
                 'هندي': 'indian',
                 'باكستاني': 'pakistani',
                 'فلبيني': 'filipino',
                 'بنغلاديشي': 'bangladeshi',
                 'مصري': 'egyptian',
                 'بريطاني': 'british',
                 'أخرى': 'other',
                 'اماراتی': 'uae_national',
                 'ہندوستانی': 'indian',
                 'پاکستانی': 'pakistani',
                 'فلپینو': 'filipino',
                 'بنگلادیشی': 'bangladeshi',
                 'مصری': 'egyptian',
                 'برطانوی': 'british',
                 'دیگر': 'other',
                 'इमिराती': 'uae_national',
                 'भारतीय': 'indian',
                 'पाकिस्तानी': 'pakistani',
                 'फिलिपीनो': 'filipino',
                 'बांग्लादेशी': 'bangladeshi',
                 'मिस्री': 'egyptian',
                 'ब्रिटिश': 'british',
                 'अन्य': 'other',
                 'iba pa': 'other'},
 'secondary_job': {'yes': 'yes',
                   'no': 'no',
                   'نعم': 'yes',
                   'لا': 'no',
                   'ہاں': 'yes',
                   'نہیں': 'no',
                   'हाँ': 'yes',
                   'नहीं': 'no',
                   'oo': 'yes',
                   'hindi': 'no'},
 'job_search_active': {'yes': 'yes',
                       'no': 'no',
                       'نعم': 'yes',
                       'لا': 'no',
                       'ہاں': 'yes',
                       'نہیں': 'no',
                       'हाँ': 'yes',
                       'नहीं': 'no',
                       'oo': 'yes',
                       'hindi': 'no'},
 'available_for_work': {'yes': 'yes',
                        'no': 'no',
                        'نعم': 'yes',
                        'لا': 'no',
                        'ہاں': 'yes',
                        'نہیں': 'no',
                        'हाँ': 'yes',
                        'नहीं': 'no',
                        'oo': 'yes',
                        'hindi': 'no'},
 'ever_worked': {'yes_in_uae': 'yes_in_uae',
                 'yes_outside_uae': 'yes_outside_uae',
                 'never_worked': 'never_worked',
                 'yes — last job was in uae': 'yes_in_uae',
                 'yes — last job was outside uae': 'yes_outside_uae',
                 'no — never worked': 'never_worked',
                 'نعم — آخر عمل في الإمارات': 'yes_in_uae',
                 'نعم — آخر عمل خارج الإمارات': 'yes_outside_uae',
                 'لا — لم أعمل أبداً': 'never_worked',
                 'ہاں — آخری کام uae میں تھا': 'yes_in_uae',
                 'ہاں — آخری کام uae سے باہر تھا': 'yes_outside_uae',
                 'نہیں — کبھی نہیں کیا': 'never_worked',
                 'हाँ — पिछला काम uae में था': 'yes_in_uae',
                 'हाँ — पिछला काम uae से बाहर था': 'yes_outside_uae',
                 'नहीं — कभी नहीं किया': 'never_worked',
                 'oo — sa uae ang huling trabaho': 'yes_in_uae',
                 'oo — sa labas ng uae': 'yes_outside_uae',
                 'hindi — hindi pa nagtrabaho': 'never_worked'},
 'platform_work': {'yes_primary': 'yes_primary',
                   'yes_supplementary': 'yes_supplementary',
                   'no': 'no',
                   'yes — primary income': 'yes_primary',
                   'yes — supplementary income': 'yes_supplementary',
                   'نعم — دخل رئيسي': 'yes_primary',
                   'نعم — دخل إضافي': 'yes_supplementary',
                   'لا': 'no',
                   'ہاں — بنیادی آمدنی': 'yes_primary',
                   'ہاں — اضافی آمدنی': 'yes_supplementary',
                   'نہیں': 'no',
                   'हाँ — मुख्य आय': 'yes_primary',
                   'हाँ — अतिरिक्त आय': 'yes_supplementary',
                   'नहीं': 'no',
                   'oo — pangunahing kita': 'yes_primary',
                   'oo — karagdagang kita': 'yes_supplementary',
                   'hindi': 'no'},
 'vocational_training': {'yes': 'yes',
                         'no': 'no',
                         'نعم': 'yes',
                         'لا': 'no',
                         'ہاں': 'yes',
                         'نہیں': 'no',
                         'हाँ': 'yes',
                         'नहीं': 'no',
                         'oo': 'yes',
                         'hindi': 'no'},
 'monthly_wage_range': {'under_5000': 'under_5000',
                        '5000_10000': '5000_10000',
                        '10001_20000': '10001_20000',
                        '20001_50000': '20001_50000',
                        'over_50000': 'over_50000',
                        'prefer_not_to_say': 'prefer_not_to_say',
                        'less than 5,000': 'under_5000',
                        '5,000–10,000': '5000_10000',
                        '10,001–20,000': '10001_20000',
                        '20,001–50,000': '20001_50000',
                        'more than 50,000': 'over_50000',
                        'prefer not to say': 'prefer_not_to_say',
                        'أقل من 5,000': 'under_5000',
                        'أكثر من 50,000': 'over_50000',
                        'أفضل عدم الإفصاح': 'prefer_not_to_say',
                        '5,000 سے کم': 'under_5000',
                        '50,000 سے زیادہ': 'over_50000',
                        'بتانا نہیں چاہتا': 'prefer_not_to_say',
                        '5,000 से कम': 'under_5000',
                        '50,000 से अधिक': 'over_50000',
                        'बताना नहीं चाहते': 'prefer_not_to_say',
                        'wala pang 5,000': 'under_5000',
                        'higit sa 50,000': 'over_50000',
                        'ayaw sabihin': 'prefer_not_to_say'},
 'highest_previous_salary': {'under_5000': 'under_5000',
                             '5000_10000': '5000_10000',
                             '10001_20000': '10001_20000',
                             '20001_50000': '20001_50000',
                             'over_50000': 'over_50000',
                             'prefer_not_to_say': 'prefer_not_to_say',
                             'less than 5,000': 'under_5000',
                             '5,000–10,000': '5000_10000',
                             '10,001–20,000': '10001_20000',
                             '20,001–50,000': '20001_50000',
                             'more than 50,000': 'over_50000',
                             'prefer not to say': 'prefer_not_to_say',
                             'أقل من 5,000': 'under_5000',
                             'أكثر من 50,000': 'over_50000',
                             'أفضل عدم الإفصاح': 'prefer_not_to_say',
                             '5,000 سے کم': 'under_5000',
                             '50,000 سے زیادہ': 'over_50000',
                             'بتانا نہیں چاہتا': 'prefer_not_to_say',
                             '5,000 से कम': 'under_5000',
                             '50,000 से अधिक': 'over_50000',
                             'बताना नहीं चाहते': 'prefer_not_to_say',
                             'wala pang 5,000': 'under_5000',
                             'higit sa 50,000': 'over_50000',
                             'ayaw sabihin': 'prefer_not_to_say'}}
